react:
  image:
    repository: ruzafa8/portfolio
    pullPolicy: Always
    tag: "latest"

  ingress:
    hosts:
      - host: alex.weasiti.foo
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
